CVE-2024-49761 waive CVE
tulibraries/funnel_cake pull request #675
Opened 2024-11-05 18:03 UTC by nomadicoder

2024-11-07 19:59 UTC, sensei100 commented
@nomadicoder This won't pass without also adding the essential_packages.txt file.

2024-11-07 20:00 UTC, sensei100 requested changes
Needs the essential_packages.txt file

2024-11-07 22:21 UTC, nomadicoder commented
@sensei100 The essential_packages.txt file already exists and already has rexml.  https://github.com/tulibraries/funnel_cake/blob/CVE-2024-49761-Waive_CVE/Documentation/essential_packages.txt

2024-11-18 16:30 UTC, sensei100 approved these changes

2024-11-18 16:30 UTC, merged